language: node_js
node_js:
  - "0.12"
  - "0.10"
  - "0.8"
  - "iojs"
before_install:
  - "npm install -g npm@1.4.x"
script:
  - "npm run lint"
  - "npm run coverage"
matrix:
  fast_finish: true
