language: node_js
node_js:
  - "0.12"
  - "0.10"
  - "iojs"
script:
- "gulp coverage"
- "gulp bundle"
- "gulp inject"
after_script:
  - "npm install coveralls@2.11.x && cat coverage/lcov.info | coveralls"
matrix:
  fast_finish: true